- tests/searchTest.js
Add support for placeholder tests (see commit message).
> immediately error on placeholder tests

- test_cases/locations.json
- test_cases/search.json
tests https://github.com/pelias/schema/pull/42
fixes pelias/pelias#43
> adding acceptance test cases for queries that has street address followed by admin info

- README.md
- output_generators/terminal.js
- run_tests.js
- test_cases/search.json
Closes #20: distinguish between expected and unexpected failures, and emit obvious alerts when the latter occurs.
> track test progress and alert on failures

- test_cases/search.json
> adding a few test cases that test popularity metric

- output_generators/email.js
When running locally it's nice to not have to send emails.
> Allow no email config

- README.md
- run_tests.js
- test_cases/reverse_categories.json
> Add test suite for /reverse and validate new categories feature

- test_cases/params_details.json
- test_cases/search_coarse.json
- test_cases/suggest.json
- test_cases/suggest_coarse.json
- test_cases/suggest_nearby.json
> Tests for details parameter

- test_cases/exact_matches.json
- test_cases/feedback_pass.json
Add test cases for pelias/api#113 and pelias/scripts#7.
Fixes pelias/scripts#5.
> Add test cases for exact matches.

- .travis.yml
- README.md
Travis should run the acceptance tests against production when merging to master.
It will email the team the results.
> Add travis run on prod

- test_cases/search.json
> Test multi_match on name.* for /search

- test_cases/search.json
Reverts pelias/acceptance-tests#48
> Revert "Test multi_match on name.* for /search"

- locations.json
- test_cases/params_details.json
Fixes pelias/api#135
Tests the new possible values.
> Details param not working as expected

- .gitignore
- locations.json
- run_tests.js
- test_cases/admin_lookup.json
- test_cases/feedback_fail.json
- test_cases/feedback_pass.json
- test_cases/params_details.json
- test_cases/reverse_categories.json
- test_cases/search.json
Working through all the failing tests to determine which, if any, are release blockers.
Closes pelias/pelias#97
> Testing ngrams

- test_cases/feedback_pass.json
this is a valid regression as per https://github.com/pelias/api/issues/151
> mark regression

- test_cases/feedback_pass.json
> fix test, less brittle

- run_tests.js
Includes a refactor so there is an array of retry codes, and adds 408 to that list.
> Return code handling

- test_cases/reverse_categories.json
> fixing prod regression by closing a bracket

- README.md
- package.json
resolves https://github.com/pelias/acceptance-tests/issues/126
> npm@2+ required

- test_cases/suggest_coarse.json
> remove duplicate test

- test_cases/landmarks.json
Statue of Liberty in NY not showing up as top result
Related to https://github.com/pelias/pelias/issues/73
> Landmark test failing

- test_cases/address_parsing.json
- test_cases/admin_lookup.json
- test_cases/search.json
> Search query builder not checking all available admin values

- test_cases/place.json
> Add test of newly renamed place endpoint

- test_cases/reverse_coordinate_wrapping.json
See the related pelias/api#121 pull request.
fixes pelias/api#56
> add test-cases for longitude wrapping

- .travis.yml
- test_cases/address_parsing.json
- test_cases/address_type.json
- test_cases/admin_lookup.json
- test_cases/categories.json
- test_cases/exact_matches.json
- test_cases/landmarks.json
- test_cases/params_details.json
- test_cases/place.json
- test_cases/quattroshapes_popularity.json
- test_cases/reverse_categories.json
- test_cases/reverse_coordinate_wrapping.json
- test_cases/search.json
- test_cases/search_coarse.json
- test_cases/suggest.json
- test_cases/suggest_coarse.json
- test_cases/suggest_nearby.json
Fixes pelias/api#201
* removed .travis.yml because it doesn't make sense to run it for this repo
* updated all the tests using this [script](https://gist.github.com/dianashk/f5a8a510f68cf63cb8a4)
> Update test endpoints, params, and responses

- package.json
> Increment version of fuzzy-tester package

- test_cases/address_parsing.json
- test_cases/address_type.json
- test_cases/admin_lookup.json
- test_cases/categories.json
- test_cases/exact_matches.json
- test_cases/landmarks.json
- test_cases/params_details.json
- test_cases/quattroshapes_popularity.json
- test_cases/search.json
- test_cases/search_coarse.json
- test_cases/suggest.json
- test_cases/suggest_coarse.json
- test_cases/suggest_nearby.json
> Rename input to text in all tests

- test_cases/address_type.json
- test_cases/place.json
- test_cases/suggest.json
Acceptance tests to go along with pelias/api#292.
Fixes pelias/api#238
Fixes pelias/api#277
> 277 3 part gids

- test_cases/labels.json
- test_cases/search.json
this is the corresponding PR for https://github.com/pelias/api/pull/301
note: I ran in to this issue https://github.com/pelias/fuzzy-tester/pull/16 while testing but I'm pretty sure they would pass if not for that.
> label generator test cases & fixes

- test_cases/admin_lookup.json
- test_cases/landmarks.json
Marked the following failure and created/linked corresponding issues:
* [Vista Center](https://github.com/pelias/api/issues/357)
* [Statue of Liberty](https://github.com/pelias/pelias/issues/171)
> Marking tests as failing for known issues

- test_cases/address_matching.json
- test_cases/address_parsing.json
Fixes pelias/pelias#172
Tests https://github.com/pelias/schema/pull/77
> Add test cases for pelias/schema/pull/77

- test_cases/autocomplete_venues.json
- test_cases/labels.json
- test_cases/search.json
Update tests to match the new German address format.
Tests https://github.com/pelias/api/pull/351
> Fix tests with German address labels

- test_cases/address_matching.json
> Postalcode should not strip leading 0s

- package.json
Use the latest fancy with the cool new concise diff output
> Use pelias-fuzzy-tester 0.5.0

- test_cases/poi_address_matching.json
> Test for address search resulting in POI result where relevant

- test_cases/autocomplete_focus.json
- test_cases/search.json
Adds tests noted by @nvkelso in pelias/pelias#183
> Adds autocomplete + search tests for SF Zoo being in SF

- test_cases/admin_lookup.json
> Add test for Vancouver admin lookup

- test_cases/autocomplete_poi.json
- test_cases/search_poi.json
Tests for Eureka, CA Target superstore, as identified by @nvkelso in pelias/pelias#185
> Adds tests for Eureka Target

- test_cases/autocomplete_admin_areas.json
@orangejulius realized that the admin areas were failing the autocomplete tests. No bueno. Here's a test!
> brooklyn autocomplete k-stem issues

- test_cases/autocomplete_streets.json
add test for issue https://github.com/pelias/api/issues/370
> add test for issue https://github.com/pelias/api/issues/370

- test_cases/autocomplete_poi.json
test for https://github.com/pelias/api/issues/287
> test for https://github.com/pelias/api/issues/287

- test_cases/address_matching.json
- test_cases/address_parsing.json
- test_cases/admin_lookup.json
- test_cases/autocomplete_admin_areas.json
- test_cases/labels.json
- test_cases/quattroshapes_popularity.json
- test_cases/search.json
- test_cases/search_coarse.json
Marked failures and created/linked the following tickets:
- pelias/api#456
- pelias/pelias#292
- pelias/pelias#293
- pelias/pelias#295
- pelias/pelias#294
- pelias/pelias#296
Also updated labels for a few places in NY.
Connected to #192
> Update tests to reflect WOF integration status

- test_cases/admin_lookup.json
- test_cases/autocomplete_admin_areas.json
- test_cases/labels.json
- test_cases/quattroshapes_popularity.json
- test_cases/search.json
- test_cases/search_coarse.json
Connected to pelias/whosonfirst#59
> Update tests to reflect recent changes.

- test_cases/address_parsing.json
- test_cases/quattroshapes_popularity.json
Similar to #214 this changes more tests to use properties other than label.
> Use properties over labels

- test_cases/admin_lookup.json
> Add Finland admin lookup test

- test_cases/search_layers.json
This was a problem with the Geonames importer for a while.
Fixes pelias/pelias#253
> Test that layers=venue only returns venues

- test_cases/wof_countries.json
> Add acceptance tests for pelias/api#166

- test_cases/autocomplete_stop_words.json
add test for https://github.com/pelias/schema/issues/105
> Mismatch in synonym analysis between ngram and phrase analyzers

- test_cases/autocomplete_jitter.json
closes: https://github.com/pelias/pelias/issues/165
> Autocomplete Jitter

- test_cases/data.json
Along with a new test suite meant for data issues.
> Add Copenhagen data test case

- test_cases/address_parsing.json
- test_cases/autocomplete_admin_areas.json
- test_cases/autocomplete_streets.json
> Mark passing tests passing!

- test_cases/properties_source_id.json
> Add tests to verify source_id is properly returned from all endpoints

- test_cases/labels.json
Add acceptance-tests for https://github.com/pelias/wof-admin-lookup/issues/49
Note: these tests won't pass until https://github.com/pelias/api/issues/569 is fixed
> Geonames labels

- test_cases/encoding.json
> New tests to check diacritics are shown in the results correctly

- test_cases/brooklyn.json
- test_cases/encoding.json
- test_cases/search.json
- test_cases/search_coarse.json
- test_cases/wof_localities.json
> Fix acceptance tests for regressions from 7/28/2016 build

- test_cases/encoding.json
Related to discussion in pelias/api#600
> Added Chambery tests

- test_cases/place.json
I was looking to take care of this on my own but realised @avulfson17 already had a commit for it. There was another commit for the other improvement, but that one has to be updated with a new postal code.
> Mark test for short GIDs passing!

- test_cases/autocomplete_boundary_country.json
Connects https://github.com/pelias/api/pull/634
Connects https://github.com/pelias/pelias/issues/403
> Add test for autocomplete boundary.country

- test_cases/tizen-sdk-geocoder.json
- test_cases/tizen-sdk-places.json
Tests show how each function in the SDK would be implemented in the wrapper. Many marked as failing because the functionality is yet to be implemented.
Connected to pelias/pelias#150
> Add new test suites for various Tizen SDK functions

- test_cases/autocomplete_street_centroids.json
- test_cases/autocomplete_street_fallback.json
- test_cases/search_street_centroids.json
- test_cases/search_street_fallback.json
ensure that `street` layer data is accessible
second commit: ensure that street record is returned before address records on the same road
> add test cases for street layer data

- test_cases/wof_dependencies.json
all place types are currently represented except for `dependency`
> added tests for WOF dependencies

- test_cases/fallback.json
> added tests for street+common city fallback

- test_cases/labels.json
> Fix Bermuda label test

- test_cases/component_geocoding.json
Initial set of component geocoding tests
Connected to pelias/pelias#417
> added component tests

- test_cases/encoding.json
- test_cases/labels.json
- test_cases/search_city_country.json
Also includes support for city/dependency.
This is to support pelias/api#730
> Add city/country tests

- test_cases/component_geocoding.json
> made switch to `locality` and `region` for component geocoding

- test_cases/address_parsing.json
- test_cases/autocomplete_streets.json
- test_cases/component_geocoding.json
- test_cases/exact_matches.json
- test_cases/properties_source_id.json
- test_cases/tizen-sdk-geocoder.json
Fixes the regressions in our latest build, see individual commits for details.
> Fix regressions

- test_cases/structured_geocoding.json
> Add structured query tests

- test_cases/structured_geocoding.json
This was supposed to be added to test pelias/query#53 but I forgot to merge it.
> added test for number+street-only input

- test_cases/structured_geocoding.json
> switched structured tests from `query` to `venue`

- test_cases/structured_geocoding.json
Manual merge so that the test fixes from https://github.com/pelias/acceptance-tests/pull/337 can make it to production.
> Merge master into staging

- test_cases/autocomplete_streets.json
> added additional expectation to autocomplete test

- test_cases/search_postalcodes.json
> Add postalcode only search tests

- test_cases/autocomplete_focus.json
This was fixed with https://github.com/pelias/api/pull/729 some time ago.
> Mark SF focus test passing

- test_cases/labels.json
- test_cases/washington_dc.json
All our DC tests now pass with some minor tweaks!
> Improvements in Washington, DC tests

- test_cases/structured_postalcodes.json
Connected to pelias/pelias#521
> Add tests for postal-code only structured query

- test_cases/geonames.json
> Add tests for geonames ids

- test_cases/search_street_centroids.json
Probably caused by a copy/paste error :P
> Fix incorrect test suite name

- test_cases/address_matching.json
- test_cases/address_parsing.json
- test_cases/exact_matches.json
- test_cases/geonames.json
- test_cases/labels.json
- test_cases/quattroshapes_popularity.json
- test_cases/wof_counties.json
- test_cases/wof_neighbourhoods.json
https://github.com/pelias/pelias/milestone/49
> Update acceptance tests related to upgrading to Libpostal 1.0.0

- package.json
> fix(package): update pelias-fuzzy-tester to version 0.9.3

- test_cases/university.json
Connects to https://github.com/pelias/pelias/issues/598
> Created set of university name parsing tests

- test_cases/reverse_coarse.json
This is a change that happened in the data recently.
https://whosonfirst.mapzen.com/spelunker/id/1108826389/
> Update Auvergne to Auvergne-Rhone-Alpes

- test_cases/placeholder_altnames.json
Tests lang parameter for search, search/structured, autocomplete, reverse, and nearby. 
Also tests different variations of languages in input (ie. address in English, admin info in French)
> Created acceptance tests for placeholder altnames

- package.json
> fix(package): update pelias-fuzzy-tester to version 0.9.11

- test_cases/admin_lookup.json
- test_cases/placeholder_altnames.json
- test_cases/search_iso2_to_iso3.json
- test_cases/structured_geocoding.json
* a few WOF records were changed (deprecated, renamed)
* one address was problematic because there were 3 version in the data and depending on order or capitalization would screw up results
* removed check for venue name where it wasn't relevant to the test
> Fix tests to match latest prod-build

- test_cases/search_iso2_to_iso3.json
- test_cases/structured_geocoding.json
This makes all the tests pass on production! 😬
> Oops! Missed pushing this commit somehow.

- test_cases/autocomplete_admin_areas.json
Connected to https://github.com/pelias/pelias/issues/646
> Mark victoria test as failing

- test_cases/international.json
- test_cases/reverse_coarse.json
Updated tests affected by new approach to wof-admin-lookup.  
Added tests for new placetypes (continent, empire, ocean, marinearea)
> Adjust tests for new admin lookup

- test_cases/address_interpolation.json
- test_cases/address_parsing.json
- test_cases/international.json
- test_cases/placeholder_altnames.json
- test_cases/properties_source_id.json
- test_cases/tizen-sdk-geocoder.json
I noticed a few tests marked as failing that are actually passing or out of date.
> Cleanup old tests

- test_cases/locality_geodisambiguation.json
Connected to pelias/pelias#565
> Locality should be checked against county/borough

- test_cases/korean_addresses.json
- test_cases/korean_admin.json
- test_cases/korean_venues.json
A lot of these are really close to passing once we rename Seoul region. Many have other issues we'll need to resolve in the future.
> Add tests for Korea

- package.json
> fix(package): update pelias-fuzzy-tester to version 0.10.4

- package.json
> fix(package): update pelias-fuzzy-tester to version 0.11.1

- package.json
> fix(package): update pelias-fuzzy-tester to version 1.0.0

- test_cases/placeholder_geometric_filters.json
test cases for https://github.com/pelias/api/pull/1175
> placeholder: geometric filter tests

- test_cases/autocomplete_acushnet_antiques.json
- test_cases/autocomplete_admin_areas.json
- test_cases/autocomplete_focus.json
- test_cases/autocomplete_jitter.json
- test_cases/autocomplete_stop_words.json
- test_cases/international.json
- test_cases/placeholder_altnames.json
- test_cases/san_francisco.json
- test_cases/search_postalcodes.json
A few tests were failing against our latest full planet build, this cleans them up.
> Periodic acceptance test cleaning

- test_cases/autocomplete_boundary_gid.json
- test_cases/search_boundary_gid.json
Some simple tests for boundary.gid!
Connects https://github.com/pelias/api/pull/1249
> Add boundary.gid tests

- test_cases/deduplication.json
- test_cases/structured_geocoding.json
Test some cases covered in https://github.com/pelias/api/pull/1230
> Add deduplication specific tests

- test_cases/admin_lookup.json
- test_cases/deduplication.json
- test_cases/international.json
WOF has changed a lot since our last production deployment, this PR tracks those changes.
> update test-cases for the latest version of wof/placeholder

- test_cases/autocomplete_synonyms.json
Connects https://github.com/pelias/pelias/issues/256
Connects https://github.com/pelias/schema/pull/350
> Test mt/mount on autocomplete endpoint

- test_cases/autocomplete_admin_areas.json
- test_cases/labels.json
- test_cases/wof_regions.json
> Placeholder updates round 2

- test_cases/search_postal_cities.json
This is just a small sample of postal city issue test cases. More can be found in https://github.com/pelias/pelias/issues/396#issuecomment-477736197
> Add postal cities test cases

- test_cases/address_type.json
- test_cases/admin_lookup.json
- test_cases/australian_addresses.json
- test_cases/autocomplete_daly_city.json
- test_cases/autocomplete_street_fallback.json
- test_cases/french_addresses.json
- test_cases/international.json
- test_cases/korean_addresses.json
- test_cases/korean_admin.json
- test_cases/labels.json
- test_cases/place.json
- test_cases/placeholder_altnames.json
- test_cases/placeholder_general.json
- test_cases/properties_source_id.json
- test_cases/search.json
- test_cases/search_abbreviations.json
- test_cases/search_city_country.json
- test_cases/search_poi.json
- test_cases/structured_geocoding.json
- test_cases/tizen-sdk-places.json
- test_cases/wof_counties.json
- test_cases/wof_macroregions.json
A bunch of updates! Lots of them are actually tests that are now passing, thanks to a lot of our recent work. Individual commits all have links to the relevant issues.
Additional Australian and French addresses have been added as a result of new cases recently discovered.
> April updates

- test_cases/autocomplete_abbreviations.json
These test issues such as the following:
https://github.com/pelias/schema/issues/335
https://github.com/pelias/pelias/issues/737
> Add autocomplete abbreviation tests

- test_cases/australian_addresses.json
- test_cases/autocomplete_abbreviations.json
- test_cases/international.json
- test_cases/labels.json
- test_cases/result_properties.json
- test_cases/search.json
- test_cases/search_focus.json
- test_cases/search_postalcodes.json
- test_cases/structured_postalcodes.json
- test_cases/tizen-sdk-places.json
The usual round of routine acceptance test updates. Lots of improvements have actually been seen over the last few months and this marks them all as passing!
There was one regression, which we intentionally made because it came with a performance improvement.
As before, see the individual commits for details.
> August updates

- test_cases/autocomplete_acushnet_antiques.json
- test_cases/autocomplete_boundary_country.json
- test_cases/autocomplete_daly_city.json
- test_cases/autocomplete_poi.json
- test_cases/autocomplete_street_centroids.json
- test_cases/autocomplete_streets.json
- test_cases/international.json
- test_cases/search.json
- test_cases/search_iso2_to_iso3.json
- test_cases/search_poi.json
- test_cases/search_street_centroids.json
- test_cases/structured_geocoding.json
- test_cases/university.json
Mostly related to https://github.com/pelias/api/pull/1287, but some others as well
> October upates

- test_cases/search_street_centroids.json
Connects https://github.com/pelias/api/pull/1322
> Add street slop test cases

- test_cases/autocomplete_admin_areas.json
- test_cases/structured_geocoding.json
- test_cases/tizen-sdk-places.json
Acceptance test updates to reflect the state-of-play for `api:master-2019-10-09-d0cf44f36f68472185d4d20c7b545ac214e4f160` tested on our staging server
resolves https://github.com/pelias/pelias/issues/646
related https://github.com/pelias/pelias/issues/482
related https://github.com/pelias/pelias/issues/293
> October updates

- test_cases/autocomplete_streets.json
- test_cases/search_iso2_to_iso3.json
- test_cases/search_poi.json
- test_cases/search_street_centroids.json
this PR updates the tests to reflect recent changes.
I have changed a couple of the `street centroid` tests because they were covering a lot more than just that.
```bash
Aggregate test results
Pass: 616
Improvements: 0
Fail: 118
```
> updates nov 2019

- test_cases/admin_lookup.json
- test_cases/placeholder_general.json
- test_cases/placeholder_sorting.json
- test_cases/reverse_coarse.json
- test_cases/search_focus.json
- test_cases/wof_counties.json
Just a couple quick January updates!
> January updates

- test_cases/search_postal_cities.json
We've recently improved our code to handle the [postal cities problem](https://github.com/pelias/pelias/issues/396) and will soon be enabling it by default!
This PR updates the acceptance tests with the new expectations. :tada:
> Postal cities updates

- test_cases/search_poi.json
Some relevant issues:
https://github.com/pelias/pelias/issues/260
https://github.com/pelias/pelias/issues/171
https://github.com/pelias/pelias/issues/783
https://github.com/pelias/pelias/issues/808
> Add test cases for several POIs

- test_cases/address_parsing.json
Connects https://github.com/pelias/api/pull/1437
> Add test for match_type behavior

- test_cases/autocomplete_multi_lang.json
Add some tests for the pelias/api#1300
related pelias/api#1296 pelias/pelias#767 pelias/pelias#699 pelias/pelias#663
> Add tests for multi lang support in autocomplete

- test_cases/admin_lookup.json
- test_cases/australian_addresses.json
- test_cases/autocomplete_boundary_rect.json
- test_cases/wof_counties.json
- test_cases/wof_localities.json
- test_cases/wof_neighbourhoods.json
Some acceptance test updates based on newer WOF data for Placeholder.
> Placeholder data updates

- test_cases/autocomplete_focus.json
These had very old labels so its clear they haven't been updated in quite some time.
> Update Union Square tests

- test_cases/search_poi.json
- test_cases/university.json
Progress is always good :)
Both of these improvements probably come from some of our venue related improvements like https://github.com/pelias/openstreetmap/pull/493 and https://github.com/pelias/api/pull/1469
> Mark two passing tests passing

- test_cases/autocomplete_address.json
- test_cases/autocomplete_iso2_to_iso3.json
- test_cases/autocomplete_postalcodes.json
We've had many acceptance tests start to pass with all our recent work :)
Fixes here came from https://github.com/pelias/schema/pull/475, https://github.com/pelias/schema/pull/473 andhttps://github.com/pelias/openstreetmap/pull/549!
> Mark tests passing

- test_cases/deduplication.json
This PR extends our existing deduplication tests with some more examples, as well as cleaning up some of the existing ones.
It's pretty hard to write deduplication related tests that aren't brittle (for example, by relying on a specific GID), so it may be that these are always fairly limited.
> Improved Deduplication test cases

- test_cases/autocomplete_endonyms.json
test cases covering https://github.com/pelias/wof-admin-lookup/pull/317
> add region endonym test cases

- .github/workflows/push.yml
Building on #569, this is an extremely simple change to validate all the test case JSON using `jq`. From my testing the error message isn't super clear, but it will at least provide a sanity check.
> Validate test JSON
