pelias/acceptance-tests

- run_tests.js
- test/test.js
- test_cases/feedback_pass.json
- test_cases/params_details.json
- test_cases/reverse_categories.json
- test_cases/search.json
* several new tests for category and address properties in details.
* change run_tests to fail tests if multiple expected results are not ALL found. that changed required test_case cleanup.
Fixes pelias/api#118
> Add categories and address properties to result doc

- test_cases/categories.json
- test_cases/feedback_pass.json
Add test-cases for pelias/geonames#22.
fixes pelias/geonames#20
```
test_cases/categories.json
-Add a bunch of test-cases for the addition of categories to
GeoNames data (see [0]).
-They aren't actually usable until the API can return
categories, so must wait until [1] gets merged.
0: https://github.com/pelias/geonames/pull/22
1: https://github.com/pelias/api/pull/122
```
> Add test-cases for geonames categories.

- run_tests.js
Regressions were being double-counted and showed up as part of the `fail` count as well.
> [BUG] Regressions were being double-counted

- test_cases/feedback_pass.json
- test_cases/search.json
All acceptance tests that were failing, even if the failure was expected, are removed.
Don't worry, they'll come back in individual pull requests.
12 tests total were removed, most from the feedback app that apparently used to be passing. One test was changed from failing to passing because it already was passing!
> Remove failing tests

- test_cases/feedback_pass.json
disambiguate `Facebook` could mean any of:
```
1) Facebook
2) Facebook, LuleÃ¥, Norrbottens län
3) Facebook, Thapathali, Bagmati
4) Facebook, HyderÄbÄd, Andhra Pradesh
5) Facebook Datacenter, Norrbottens län
6) Facebook Campus, Menlo Park, CA
7) facebook restuarant, AhmadÄbÄd, Gujarat
8) FACEBOOK Bar, Lagunes
9) Facebook Bar, Addis Ababa
10) Facebook France, PARIS-17E-ARRONDISSEMENT, Paris
11) Facebook HQ, Menlo Park, CA
12) Facebook Boston, Cambridge, MA
13) One Facebook Way, Menlo Park, CA
14) Facebody, KÃ¸benhavn, Hovedstaden
15) Facebook Data Center, Prineville, OR
16) Facebook Advertisement Nepal, Thapathali, Bagmati
17) Facebook Ireland Ltd, Dublin, Dublin City
```
> fix test, less brittle

- test_cases/feedback_pass.json
1426636804303:9, target admin entry and geoname record only
> 1426636804303:9, target admin entry and geoname record only

- package.json
- run_tests.js
This PR marks a test case as a failure if the API response does not have a results object and avoid the following error
```
TypeError: Cannot read property 'length' of undefined
at evalTest (/Users/harishkrishna/code/pelias/acceptance-tests/run_tests.js:46:18)
at Request._callback (/Users/harishkrishna/code/pelias/acceptance-tests/run_tests.js:220:21)
at Request.self.callback (/Users/harishkrishna/code/pelias/acceptance-tests/node_modules/request/request.js:368:22)
at Request.emit (events.js:98:17)
at Request.<anonymous> (/Users/harishkrishna/code/pelias/acceptance-tests/node_modules/request/request.js:1219:14)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous> (/Users/harishkrishna/code/pelias/acceptance-tests/node_modules/request/request.js:1167:12)
at …
```
> fail fast if apiResults doesnt exist

- lib/ExponentialBackoff.js
- run_tests.js
In order to keep our tests from completely killing our production or
staging servers, this change uses a simple [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff)
algorithm to increase the delay between requests when we get error codes
like 408 that indicate our server is overloaded.
> Use exponential backoff when running tests

- test_cases/address_parsing.json
Mark failing test as a known bug. The test was relying on the order in which the data
was being imported. Coincidently it exposed a bug in the search query building logic
with regard to admin field matching.
See [issue](https://github.com/pelias/api/issues/187) for more details
> Search query builder not checking all available admin values

- test_cases/address_parsing.json
- test_cases/address_type.json
- test_cases/admin_lookup.json
- test_cases/categories.json
- test_cases/exact_matches.json
- test_cases/landmarks.json
- test_cases/params_details.json
- test_cases/quattroshapes_popularity.json
- test_cases/reverse_categories.json
- test_cases/search.json
- test_cases/search_coarse.json
- test_cases/suggest.json
- test_cases/suggest_coarse.json
- test_cases/suggest_nearby.json
this PR fixes some of the more brittle tests so they don't fail on every new release.
- set suite `priorityThresh` to 5 for all cases
- remove all per-test `priorityThresh` settings
- mark non-authoritative places such as `chelsea` failed [chelsea is very common](http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/search%3Fsize=40&input=chelsea)
- create authoritative versions of the above eg. `chelsea, ny`
- fix one or two minor errors where the wrong record was being asserted
with this configuration both production and bigdev pass
> loosen test strictness, mark non-authoriative names

- package.json
- test_cases/address_parsing.json
- test_cases/address_type.json
- test_cases/admin_lookup.json
- test_cases/categories.json
- test_cases/exact_matches.json
- test_cases/landmarks.json
- test_cases/params_details.json
- test_cases/quattroshapes_popularity.json
- test_cases/reverse_categories.json
- test_cases/search.json
- test_cases/search_coarse.json
- test_cases/suggest.json
- test_cases/suggest_coarse.json
- test_cases/suggest_nearby.json
Changelog:
* search uses all admin values in query when parsing address
* upgrade to latest fuzzy-tester
* loosen test strictness to allow phrase slop changes to pass
> Merge latest changes to production

- test_cases/params_details.json
In the case of `details` param tests, we can be really explicit with the input to ensure the same item is received each time.
> Add more input parameters to make tests less fragile

- test_cases/search.json
Tests to go along with pelias/api#205. It uses our beloved statue of liberty query, but with an alpha3 filter. The USA filtered query should only return results in New York, while the FRA filtered query should only show ones in Paris.
Fixes pelias/api#112
> Add admin3 filter tests

- package.json
- test_cases/search.json
Paris currently fails due to large cities with population data rank higher than cities in the viewport.
> added viewport tests for "Paris", "Lancaster", and "Manchester".

- test_cases/search.json
This reverts commit 969df26205dfac5b36f95e393daab4a44bd64ef9.
The test fails because the 4th and king station shows far too down in
the search results.
> Add 4th and king caltrain test

- test_cases/confidence_score.json
This test lists a confidence score of 0.5 as an unexpected property. We
don't have > or < comparisons in our test suite, but I think the odds of
a well formed address query that we have good data for being given a
confidence score of 0.5, other than by hitting a deal-breaker (which
caps the score to exactly 0.5), is unlikely enough that this test will
work.
Fixes pelias/api#369
> Add confidence score test

- test_cases/autocomplete_admin_areas.json
Fixes to Autocomplete admin areas tests needed so we can move pelias/api#378 & pelias/schema#84 into production.
These tests do not change the contents being returned, they just accept a broader set of valid labels for the place.
NOTES:
* [Victoria tests](https://github.com/pelias/acceptance-tests/commit/9971f8b6ad747d8b15157487f3792ab775f80d76#diff-6cbcf8faa91cd82ddffde879e25ca8da) name the city of Victoria "VICTORIA" due to a data issue in Quattroshapes. At present, this appears to be [resolved in Who's on First](https://github.com/whosonfirst/whosonfirst-data/commit/a0f71eb491bddc36a09ae379bce271e78eb14513)
> Autocomplete areas fix

- test_cases/autocomplete_focus.json
As detected by tests for pelias/schema#84 / pelias/api#378, autocomplete (& search) for Union Square return addresses on Union Square and __not__ the POIs. This issue is to be addressed in pelias/pelias#202 (POI vs Address Fights in Union Square)
These issues need to be resolved, but for the build to go through, we're disabling them for the time being.
> disables Union Square address tests

- test_cases/admin_lookup.json
Now that Vista and center are no longer stop words, this test passes!
> Change "Vista Center" test back to pass

- test_cases/autocomplete_admin_areas.json
Redefines Autocomplete Admin Areas test for San Francisco to work from document properties, and not just the label, making it less brittle.
Accepts anything that's a `locality` named `San Francisco` in `county: San Francisco County`, `region: California`.
> minimal sf test

- test_cases/autocomplete_streets.json
Tests for pelias/api#372, which is part of Autocomplete Omnibus (pelias/pelias#165)  (pelias/api#378) / (pelias/schema#84)
Fixes pelias/api#372 (since the only thing left is tests)
> Adds test cases for autocomplete term extension

- test_cases/brooklyn.json
- test_cases/san_francisco.json
Test all combinations of
layers=locality/layers=locality,localadmin/layers=[unset] against the
search and autocomplete endpoints for SF and Brooklyn.
boundary.country=USA is set for all tests.
> The ultimate SF and Brooklyn test suite

- test_cases/autocomplete_focus.json
@randymeech ran into this incident while doing a demo. Not good when it can't find the building you're in.
Found in pelias/pelias#240
[Compare Link](http://pelias.github.io/compare/#/v1/autocomplete%3Ffocus.point.lat=40.744131&focus.point.lon=-73.990424&text=1%20madison%20ave)
> Local autocomplete not finding 1 Madison Ave

- test_cases/autocomplete_streets.json
a test was failing on production, the case had a `priorityThresh` of 1, so I changed it to 3.
it seems like in the past for the query `/v1/autocomplete?text=424 Clay Av` the top result was:
```
424 Clay Avenue, Waco, TX
```
... and now the order on production is:
```
1)	424 Clay Avenue, Rochester, NY
2)	424 Clay Avenue, Waco, TX
3)	424 Clay Avenue, Bonhomme, MO
4)	424 Henry Clay Avenue, New Orleans, LA
```
... and on prodbuild it is:
```
1)	424 Clay Avenue, Bonhomme, MO
2)	424 Clay Avenue, Waco, TX
3)	424 Clay Avenue, Rochester, NY
4)	424 Henry Clay Avenue, New Orleans, LA
```
... and on dev it is:
```
1)	424 Clay Avenue, Bonhomme, Missouri
2)	424 Clay Avenue, Rochester, New York
3)	424 Clay Avenue, Waco, Texas
4)	424 Henry Clay Avenue, New Orleans, Louisiana
```
it seems to vary …
> increase priorityThresh to 3 for autocomplete_streets.json

- test_cases/search.json
Brooklyn IS King's County, so I suspect this expectation was just here
because it was a result we returned. Our label generation is better now.
> Remove "Brooklyn, King's County" expected value

- test_cases/admin_lookup.json
This test isn't concerned with individual sources. While ideally we
would want the WOF record first, the Geonames record is also fine.
> Remove source field from admin lookup test

- test_cases/admin_lookup.json
A search query for "mission, CA" is both not very specific, and probably
not how anyone in SF would search for the Mission.
> Improve Mission District, SF test

- test_cases/missing_postcodes.json
The first test is a case where the user has entered an incorrect, but
nearby zipcode for a document where we have the correct zipcode. We
should be able to figure things out anyways.
The second test has the user enter the correct zipcode, but the correct
document is missing zipcode info. We should also handle this just fine.
> Add test cases for missing and incorrect postcodes

- test_cases/address_parsing.json
- test_cases/admin_lookup.json
- test_cases/autocomplete_admin_areas.json
- test_cases/autocomplete_focus.json
- test_cases/autocomplete_venues.json
- test_cases/labels.json
- test_cases/quattroshapes_popularity.json
- test_cases/search.json
Fix all the labels that are affected by pelias/api#497 and pelias/api#507
Note: I changed many of the search tests to avoid using labels, and moved a few label checks into the label test suite instead.
> Label fixes

- test_cases/autocomplete_admin_areas.json
- test_cases/autocomplete_focus.json
- test_cases/autocomplete_streets.json
- test_cases/search_spelling_mistakes.json
more tests for autocomplete milestone
- [autocomplete] find Paris and London by partially completed tokens 'Pari' and 'Londo' (https://github.com/pelias/pelias/issues/143)
- [autocomplete] tighter focus clustering
- [autocomplete] allow users to specify the house number in the 1st 2nd or 3rd position 
- [search] find New York via misspelling "neu yorp"
> more tests for autocomplete milestone

- test_cases/autocomplete_streets.json
related: https://github.com/pelias/api/pull/526/commits/ca0c51b0fde45c3f863a516bc923bc122c68f7ee
prior to the above commit we would strip all trailing single tokens from a query; regardless of whether they were alpha or numeric.
in some recent changes to pelias/schema we have enabled the indexing of single numeric digits, this is in order to allow matching single digit house numbers.
this test ensures that the functionality mentioned above is working as expected and doesn't regress.
```
/v1/autocomplete?text=grolmanstr 8
1)	Grolmanstraße 1, Köln, Germany
2)	Grolmanstraße 7, Köln, Germany
3)	Grolmanstraße 1, Berlin, Germany
4)	Grolmanstraße 4, Köln, Germany
5)	Grolmanstraße 3, Köln, Germany
6)	Grolmanstr. 9, Köln, Germany
7)	Grolmanstraße 8, Bochum, Germany
8)	Grolmanstr. 4, Köln, Germany …
```
> test for query ending in single digit

- test_cases/address_matching.json
- test_cases/autocomplete_streets.json
These tests cover a bug where `borough` was not being correctly targeted during query execution.
the tests cover both `/v1/autocomplete` and `/v1/search`
> autocomplete and search tests for borough matching

- test_cases/autocomplete_focus.json
This captures both the issue we've had in the past showing NYC in the
results, as well as the regression that just popped up on prodbuild.
> Add test for NYC from Stamford, CT

- test_cases/autocomplete_focus.json
- test_cases/missing_postcodes.json
- test_cases/poi_address_matching.json
- test_cases/search_coarse.json
Several of our failing tests were still looking for NYC boroughs in the
localadmin field!
:warning: Note: I just enabled LGTM for this repo so I need two LGTM, :+1:, or :shipit: responses :)
> Use borough field for New York City boroughs

- test_cases/autocomplete_admin_areas.json
- test_cases/search.json
- test_cases/search_poi.json
A few of our tests had `priorityThresh` set in the wrong place. It only has an effect if it's set in the `expected` section of the test case, not at the top level of the test case itself. This fixes all such cases and marks one test failing that now fails as a result.
As an aside, it feels like the `priorityThresh` setting might be more intuitive when set in the test case, not the test case's expected section. Should we modify the fuzzy-tester to support both?
> Fix priorityThresh configuration

- test_cases/address_parsing.json
- test_cases/admin_lookup.json
- test_cases/balance.json
- test_cases/labels.json
We've had some tests switch back to pass lately, so this updates them.
The postal code test is left with status fail because we need a new test
case.
> Mark passing tests passing!

- test_cases/san_francisco.json
Require that SF results are within 1km of the Mapshaper label centroid
of San Francisco. The Geonames centroid is a few hundred meters away,
and the math centroid of all of SF (including the Farallon islands) is
about 28km away.
Helps prevent another https://github.com/pelias/pelias/issues/356
> Add San Francisco label centroid to SF tests

- test_cases/admin_lookup.json
Since we [changed the max radius for reverse](https://github.com/pelias/api/pull/549),
this test has been failing. The second part of the work to improve
reverse is to fall back to point-in-polygon lookup of admin areas if
there are no venues or POIs nearby, which has yet to be done.
> Mark coarse reverse test failing

- test_cases/address_parsing.json
There is an extra space in the open addresses data. Until we improve the importer to handle extra spaces, this test is marked as failing.
> Change test expectation to failing due to extra space

- test_cases/autocomplete_daly_city.json
Similar to #246, we were incorrectly specifying a `priorityThresh` of 1 in all of these Daly City tests. The `priorityThresh` option has to be at the top level of the file, or in the `expected` block of an individual test.
In any case, what we wanted here was for all the tests in this file to have `priorityThresh` 1, which is now specified at the top of the file. It turns out the very first test, which has input text of only `dal`, doesn't pass with `priorityThresh` 1. Since it's a very short input, I changed the threshold for just that test to 3.
> Fix priority thresh for daly city

- test_cases/address_parsing.json
- test_cases/reverse_coordinate_wrapping.json
Work done to improve our selection of neighbourhoods for admin lookup (https://github.com/pelias/wof-pip-service/pull/36) had the unintended effect of removing some legitimately good neighbourhoods. This should be fixed by https://github.com/pelias/wof-pip-service/pull/41, but until that's merged we want the tests to pass.
There were two groups of tests failing:
1.) Reverse coordinate wrapping tests that specified a neighbourhood. I marked these failing and referenced https://github.com/pelias/wof-pip-service/issues/40.
2.) An address parsing test that looked to be a bit overspecified. I cleaned up the test to be less brittle and it now passes. We shouldn't have to worry about that one again. See more details in the [commit message](https://github.com/pelias/acceptance-tests/commit/1b35f7a …
> Mark neighborhood tests failing

- test_cases/admin_lookup.json
- test_cases/autocomplete_daly_city.json
- test_cases/autocomplete_poi.json
- test_cases/quattroshapes_popularity.json
- test_cases/reverse_coordinate_wrapping.json
- test_cases/search.json
- test_cases/search_spelling_mistakes.json
- test_cases/wof_localadmins.json
this PR contains the acceptance test changes for the new elasticsearch 2 build.
note: I accidentally included some fixes for an unrelated feature, the following tests were actually failing on elasticsearch <2
```
✘ regression [5] "{ "text": "new york, new york" }": score 9 out of 10 diff: priorityThresh is 5 but found at position 6
✘ regression [3] "{ "layers": "coarse", "text": "ridgewood" }": score 10 out of 11 diff: priorityThresh is 5 but found at position 6
✘ regression [3-1] "{ "layers": "coarse", "text": "ridgewood, ny" }": score 4 out of 5 diff: priorityThresh is 5 but found at position 8
```
anyone have any idea why there are so many commits on this PR? is it because I branched `production`?
> elasticsearch2

- test_cases/address_parsing.json
- test_cases/reverse_coordinate_wrapping.json
- test_cases/san_francisco.json
- test_cases/search_coarse.json
Tests that were failing due to an incorrect San Francisco centroid, extra whitespace, and the neighbourhood filtering issue are now all passing!
> Mark improvements passing

- test_cases/place.json
The shortened sources acceptance test currently fails when it should pass.
Fixes https://github.com/pelias/api/issues/441
> Added description for failing test

- test_cases/autocomplete_focus.json
I realized we did not have an acceptance test for this case, even though
we had other similar ones such as https://github.com/pelias/acceptance-tests/pull/232.
Connects https://github.com/pelias/acceptance-tests/issues/243
Connects https://github.com/pelias/pelias/issues/330
> Add autocomplete test for "San Francisco" with focus in NYC

- test_cases/admin_lookup.json
The name before was a #-delimited multivalue, this updates to the latest name
> fixed macroregion name to mirror current WOF record

- test_cases/admin_lookup.json
Somehow this was messed up in the [pull request that created this test](https://github.com/pelias/acceptance-tests/pull/217). The expected
locality didn't match the input string!
Note: this test has been updated with the new region name from `prod_build`, so it won't pass on prod yet.
> Correct locality and region in test

- test_cases/autocomplete_boundary_country.json
The autocomplete results for this query aren't perfect, but the main
thing we care about for the purposes of this test is the
boundary.country functionality. Setting priorityThresh to 10 makes
things ok.
> Fix autocomplete boundary.country test

- test_cases/search_street_fallback.json
Looks to have just been a little copy paste error.
> Fix name of search street fallback test suite

- test_cases/search.json
This test exercises the behavior where `size=1` was supplied along with an input containing an address that happened to score lower than a fallback query.
> Add test for fallback size anomaly

- test_cases/search_street_fallback.json
These were failing due to two things unrelated to the intent of these tests.
1.) https://github.com/pelias/pelias/issues/442, which will be tested separately
2.) Updates to our text analysis via libpostal that now allow us to return only streets (no addresses) when there is no housenumber in the query :tada: :balloon:
> Make street tests pass

- test_cases/encoding.json
After https://github.com/pelias/api/pull/687 the API will prefer to
return WOF records if they are found to be a duplicate of a Geonames
record.
> Allow encoding test results to come from any source

- test_cases/labels.json
These are label tests for a mixture of US and non-US localities in dependencies (for pelias/labels#3 and pelias/labels#5, respectively).
> added tests for labels in dependencies

- test_cases/autocomplete_boundary_rect.json
This is a search for San Francisco, with a bounding box that covers part
of Mexico (that contains a San Francisco). It checks that the results
have Mexico as the country, but not USA.
Connects https://github.com/pelias/api/pull/703
> Add test for autocomplete with boundary.rect

- test_cases/wof_localadmins.json
Aliquippa, PA is both a locality and localadmin which is causing confusion with some tests.  Zickrick, SD is *only* a localadmin so it's more appropriate for a test that's only testing localadmins.
> changed input to be unambiguously localadmin

- test_cases/search_geodisambiguation.json
Once we start supporting geodisambiguation, we'll need a place for tests; this starts it.
> Add geodisambiguation tests

- test_cases/labels.json
Replaced country names with dependency names in label tests.  
See pelias/labels#10
> fixed dependency labels

- test_cases/address_parsing.json
- test_cases/search_iso2_to_iso3.json
These tests verify that an ISO2 country code identified by libpostal can be matched (currently manually converted but should carry on once Pelias supports ISO2 in data as an altname).
> added iso2->iso3 country code conversion to /search endpoint

- test_cases/admin_lookup.json
- test_cases/component_geocoding.json
- test_cases/encoding.json
- test_cases/wof_regions.json
moved wof_region#8 test to component_geocoding to show that it still works as a region despite libpostal parsing as a city/country.  
See pelias/text-analyzer#18
> marked diacritical tests passing now

- test_cases/component_geocoding.json
Exercises the ways that the API interprets the results of libpostal. 
See pelias/api#736
> Libpostal parses address in component

- test_cases/search_mount_saint_fort_standardization.json
Tests that the following translations happen:
* Saint -> St
* Sainte -> Ste
* Ft -> Fort
* Mt -> Mount
See pelias/api#767 and pelias/schema#157
> added tests for mt/st/ft standardization

- test_cases/structured_geocoding.json
As mentioned in https://github.com/whosonfirst-data/whosonfirst-data/issues/570,
the record for Chongqing has been deprecated and a new one created. This
new one has a different default name, so the test has to change.
> Replace deprecated record in structured tests

- test_cases/structured_geocoding.json
This ensures that the address can't possibly correspond to a valid
location on the street, and the interpolation service will not return
any results.
> Change fallback query address to a large value

- test_cases/labels.json
- test_cases/washington_dc.json
This PR adds test cases for Washington, D.C. addresses and venues. It includes tests for proper label generation, ability to search when abbreviating "District of Columbia", and the possibility of incorrectly displaying "S Street" as "South Street".
The test cases are taken from these issues:
https://github.com/pelias/pelias/issues/509
https://github.com/pelias/labels/issues/14
https://github.com/pelias/pelias/issues/329
> Add test cases for Washington, D.C.

- .travis.yml
- package.json
Our acceptance tests were failing because they were running slowly, and they were running slowly because the API key configuration that's shoehorned into travis was setting the key for the wrong domain.
This PR fixes the domain and also adds a helpful config script inspired by @trescube. It was used to help make sure things were set up correctly, so I kept it around.
> Set API key for running acceptance tests on Travis correctly

- test_cases/address_parsing.json
- test_cases/admin_lookup.json
- test_cases/autocomplete_street_centroids.json
- test_cases/geonames.json
- test_cases/search.json
- test_cases/search_street_centroids.json
- test_cases/structured_geocoding.json
- test_cases/wof_neighbourhoods.json
Lots has changed in acceptance test land.
Some highlights:
* Weeksville is now a microhood, not a neighbourhood
* The Mission is now a macrohood, not a neighbourhood
* W 26th St has split in two
* SoHo was accidentally renamed Soho
> Update acceptance tests

- test_cases/autocomplete_boundary_country.json
This test doesn't actually care that London in particular shows up, but
is meant to ensure that results in the specified `boundary.country` are
the only ones that appear.
> Update expectations for autocomplete boundary.country test

- test_cases/structured_geocoding.json
geonames updates are causing our tests to do strange things
> set `sources=wof` for structured localadmin tests

- test_cases/autocomplete_admin_areas.json
- test_cases/brooklyn.json
- test_cases/search.json
It's unfair to expect Brooklyn NY to show up first in the results when the query just has `brooklyn` or `broo` and no other geographical information is given.
> Update expectations for Brooklyn test without additional geo-context

- test_cases/address_interpolation.json
adds 5 passing and 3 failing tests cases for interpolation.
the 3 failing tests are due to:
- failures when specifying size:1
- failures when admin info omittted
- failures when interpolation service queried directly but not via `pelias/api`
```
Aggregate test results
Pass: 5
Improvements: 0
Fail: 3
Placeholders: 0
Regressions: 0
Took 81ms
Test success rate 100%
```
> interpolation test cases

- test_cases/reverse_address.json
- test_cases/reverse_coarse.json
These test cover:
- fallback to coarse reverse (PiP) when there are no non-coarse results
- only request non-coarse from ES regardless of `layers` parameter
> added tests for coarse fallback and non-coarse first pass

- test_cases/international.json
This set of acceptance tests asses how well Pelias does with addresses outside of the US. 
Source: https://www.usembassy.gov/
One passing address query from each country (10 total). India did not have any address that passed (from the selection of US Embassy addresses)
The other 8 fail for these reasons: 
1. Non-English abbreviation for street, avenue, etc
2. Brazilian street-intersection address format
3. Missing locality data for an address
4. Venue name has abbreviation in parens. "Bandra Kurla Complex (BKC)" Not including the abbreviation (Bandra Kurla Complex) returns a neighborhood.
5. Street exists in OSM data but returns various addresses instead of street centroid
6. Including neighborhood in address causes falling back to locality. Referenced in …
> Addresses for AUS, BRA, CAN, DEU, ESP, FRA, GRB, MEX, RUS, ITA

- test_cases/structured_address_parsing.json
Only adding a single sample test but this is representative of the issue we were seeing.
There are two tests: one to indicate that there is no longer a 500 coming back, and the other to document that the actual response while not an error is not correct. The second test is marked failing until we resolve the underlying issue.
> Tests for 500 response for some structured queries

- test_cases/address_matching.json
- test_cases/autocomplete_streets.json
- test_cases/structured_geocoding.json
- test_cases/university.json
There are 2 reasons for this:
- due to https://github.com/whosonfirst-data/whosonfirst-data/issues/750, dependencies not longer have countries in their hierarchies
- OSM was loaded after OA, causing minor changes in result ordering
> Remove country from dependencies

- test_cases/structured_postalcodes.json
The search should return the postalcode, not fall back to country.
Connects https://github.com/pelias/api/issues/973
> Test for structured postalcode/country search

- test_cases/autocomplete_streets.json
Duplicate results for the autcomplete query `90 Vermilyea Ave` and its shorter variants have been appearing for some time. In some builds the order returned from Elasticsearch is different, so expect both results as the top two.
> Expect both Ave and Avenue variants of address

- test_cases/labels.json
- test_cases/reverse_coarse.json
- test_cases/wof_neighbourhoods.json
This PR updates our acceptance tests for PIP related changes.
There is one case of a previously working test failing because the new admin lookup strategy has exposed a broken WOF hierarchy, as well as some name changes. One other test is changed to reflect an updated hierarchy, which may have also been because of our admin lookup changes.
> Point in Polygon related test tweaks 2017-09-26

- test_cases/admin_lookup.json
- test_cases/autocomplete_admin_areas.json
- test_cases/encoding.json
- test_cases/international.json
- test_cases/labels.json
- test_cases/placeholder_altnames.json
- test_cases/placeholder_general.json
- test_cases/placeholder_sorting.json
- test_cases/search_city_country.json
- test_cases/structured_geocoding.json
- test_cases/university.json
- test_cases/wof_counties.json
- test_cases/wof_localadmins.json
- test_cases/wof_macroregions.json
- test_cases/wof_neighbourhoods.json
This PR adjusts our acceptance tests for all recent Placeholder changes.
In general, many translations have been updated and in many cases English translations have been added, often ones that have no accents or diacriticals.
A few regressions have happened, mostly around sorting such as https://github.com/pelias/placeholder/issues/55.
Two tests are temporarily marked failing because the names somehow had trailing spaces added, but both cases have been fixed via Boundary Issues and should resolve soon.
With this, combined with the changes in https://github.com/pelias/acceptance-tests/pull/434 and https://github.com/pelias/acceptance-tests/pull/437, which handle PIP and empire/dependency related issues respectively, we should be pretty much back to zero failing tests.
This PR can be tested …
> Adjust tests for mostly Placeholder changes

- test_cases/reverse_venue.json
Until we finalize the `/nearby` endpoint, `/reverse` should be able to return venues, including Geonames venues.
Once `/nearby` is ready, we can remove this support and have `/reverse` support only address and coarse results, as specified in the [design document](https://github.com/pelias/pelias/wiki/Reverse-Geocoding,-Part-Deux).
This PR adds tests for returning venues, both Geonames and OSM, from `/reverse`.
Connects https://github.com/pelias/api/issues/930
> Add tests for `/reverse` endpoint's ability to return venues

- .travis.yml
The TravisCI jobs for the pelias/acceptance-tests repo have historically
passed only if running all the tests against Mapzen Search production
passed.
There were many problems with this:
1. Branches with acceptance tests for new features would always fail
2. If there was any issue with Mapzen Search, the tests could fail
3. It assumed Mapzen Search will continue to exist!
As of today, number 3 in that list is no longer true, so now the
acceptance tests will always fail in Travis.
This PR changes the Travis tests to instead perform the same checks as
our precommit hooks: validate that the NPM package installation looks
good, and the code in this repo doesn't violate our JSHint rules.
Connects https://github.com/pelias/pelias/issues/703
> Run precommit checks on TravisCI instead of calling Mapzen Search

- test_cases/structured_geocoding.json
As noted in https://github.com/pelias/api/issues/1077, there were previously issues with Saint. Searching for "St" would fix things.
> Test structured endpoint handling of Saint

- test_cases/search_sources.json
These test cases test that the `sources` filter properly applies to admin areas, as described in https://github.com/pelias/pelias/issues/670.
Closes #471 
@tiranno this includes all your fixes. We already have tons of Portland tests, so I picked a variety of placenames from around the world. Thanks much for these great tests.
> Source filter tests

- test_cases/french_addresses.json
I tried to use addresses as the end users would type them, with abbreviations, no hyphens, etc.
Some of these addresses pass on master. Others don't because the abbreviations are not recognized (r for "rue", av for "avenue", bd for "boulevard", etc.)
Some tests fail because of the hyphen in the street name ("gay lussac" vs "gay-lussac"). This is not an issue for the city names as placeholder apparently takes care of it.
Is that what you had in mind ? Feel free to tell me if I should add more test cases or modify any.
> Start a new test suite for french addresses

- test_cases/autocomplete_street_centroids.json
- test_cases/labels.json
- test_cases/placeholder_altnames.json
- test_cases/search_postalcodes.json
- test_cases/search_street_centroids.json
- test_cases/structured_geocoding.json
- test_cases/structured_postalcodes.json
- test_cases/tizen-sdk-places.json
Test results always drift over time, and it's been quite a while since we've done this.
> Clean up and update failing tests

- test_cases/confidence_score.json
Add more confidence score tests for various cases.
The intent is to handle lots of cases from https://github.com/pelias/api/pull/1224
> feat(confidence scores): Add tests for confidence score cases

- test_cases/search_focus.json
We don't have many `focus.point` tests, especially for search.
In particular, this tests for searching for postal codes as mentioned in https://github.com/pelias/api/issues/1206, which is a good test case for `focus.point` queries over a long distance with records that otherwise score identically.
> Add search focus.point tests

- test_cases/autocomplete_admin_areas.json
- test_cases/labels.json
- test_cases/search_city_country.json
- test_cases/search_coarse.json
- test_cases/search_geodisambiguation.json
- test_cases/search_postalcodes.json
- test_cases/structured_geocoding.json
- test_cases/wof_counties.json
- test_cases/wof_regions.json
This is your regularly scheduled acceptance test update. It includes a few minor improvements to some tests, and updates tests that are now passing.
The most significant change is that thanks to https://github.com/pelias/api/pull/1230 many queries returned results that are improved via deduplication. Often this results in more-granular results (such as a locality instead of a locality and county with the same name).
> Periodic cleaning

- package.json
- test_cases/address_matching.json
- test_cases/address_parsing.json
- test_cases/australian_addresses.json
- test_cases/placeholder_altnames.json
- test_cases/tizen-sdk-geocoder.json
- test_cases/wof_localadmins.json
This is another round of updates to acceptance-tests to account for changes in Pelias behavior and data. See the individual commits for details.
One notable change is that the test now use the `trim` normalizer introduced in https://github.com/pelias/fuzzy-tester/pull/164, so the latest version of `pelias-fuzzy-tester` is now a requirement.
> February updates

- test_cases/admin_lookup.json
- test_cases/autocomplete_admin_areas.json
- test_cases/deduplication.json
- test_cases/placeholder_general.json
- test_cases/placeholder_sorting.json
- test_cases/reverse_coarse.json
- test_cases/search.json
- test_cases/search_abbreviations.json
- test_cases/structured_geocoding.json
- test_cases/tizen-sdk-places.json
- test_cases/university.json
- test_cases/wof_counties.json
- test_cases/wof_localadmins.json
- test_cases/wof_localities.json
- test_cases/wof_macroregions.json
- test_cases/wof_neighbourhoods.json
- test_cases/wof_regions.json
This PR started out as an update to improve the acceptance test results based on more up to date data in Placeholder (the dataset we generally ran them against is a few months old), but it's expanded to include numerous other fixes.
Labels for London and New York were re-evaluated, and many abbreviation related tests were added or improved, to correspond with work in https://github.com/pelias/schema/pull/356 andhttps://github.com/pelias/schema/pull/355
> March updates

- test_cases/labels.json
- test_cases/result_properties.json
- test_cases/search_poi.json
- test_cases/structured_geocoding.json
They all seem to be connected to popularity or focus points.
Perhaps related to https://github.com/pelias/api/issues/1205
> Mark tests failing with ES5

- test_cases/admin_translations.json
- test_cases/venue_translations.json
As of https://github.com/pelias/api/pull/1301, it is now possible to _return translated results_ when searching for venues.
This adds a new test suite of venue translation test cases, and renames the `placeholder altnames` test case to `admin translations` to match it.
Connects https://github.com/pelias/api/pull/1301
Connects https://github.com/pelias/api/issues/1296
> Add venue translation test cases

- test_cases/international.json
- test_cases/locality_geodisambiguation.json
Thanks to https://github.com/pelias/api/pull/1344 we hopefully now have
a definitive list of countries where the housenumber comes after the
street name.
This commit updates our acceptance tests accordingly
> Use correct address format globally

- test_cases/alphanumeric_housenumber.json
This adds 9 new test cases for housenumbers that contain non-numeric characters such as letters and punctuation.
It was written to further test https://github.com/pelias/schema/pull/379 but is also useful on its own.
The best way to explore these tests might be with autocomplete mode, where the output shows several areas to investigate to improve results:
Connects https://github.com/pelias/pelias/issues/833
> Add test cases for alphanumeric housenumbers

- test_cases/search_poi.json
This is a good test of POI ranking since there are many similarly named POIs: bus stops, rental cars, etc. There is also a smaller but well known airport elsewhere in Phoenix. The international airport _should_ be ranked higher than all those.
Finally, the official airport name is not commonly searched exactly (people leave out "sky harbor"), further testing our alt name and matching abilities. 
Related issues: 
https://github.com/pelias/pelias/issues/260
https://github.com/pelias/pelias/issues/862
> Add tests for Phoenix Airport

- test_cases/search.json
After https://github.com/pelias/fuzzy-tester/pull/192, test cases without a `status` will be assumed to _pass_. It turns out we had a test that was failing.
This change updates that expectation so the test suite behavior stays the same.
> Add missing expectation that test will fail

- test_cases/autocomplete_focus.json
Some of the expectations for queries for NYC were no longer accurate, and thanks to https://github.com/pelias/fuzzy-tester/pull/194 it was easy to see where we could improve the tests.
Two more tests are now passing!
> Use better coordinate and distanceThresh values

- test_cases/balance.json
I was wondering why no tests alerted us of the focus point balance issues in https://github.com/pelias/pelias/issues/849 and https://github.com/pelias/openstreetmap/issues/507.
It turned out that the `priorityThresh` value in the relevant tests was too generous.
This is now changed and we should be able to tell if/when progress is made.
> Increase strictness of balance tests

- test_cases/landmarks.json
This test has had an incorrect label, last updated in 2016, so it was showing as failed even when it is actually much improved with venue popularity changes.
> Improve Statue of Liberty test

- test_cases/autocomplete_jitter.json
This handles minor differences in the order of records with `st` vs `street` in the results.
> Use abbreviation normalizer in autocomplete jitter tests

- test_cases/fallback.json
Fallback behavior is a core part of Pelias: rather than just returning any results that match some of the search terms, we want Pelias to return results with some knowledge of the hierarchy of elements in the query.
This adds a test case confirming the behavior that, when given a query for a street in a city, but the street doesn't exist Pelias returns the city.
The undesired behavior is that other streets with the same name in other cities are returned.
Here's an example of the correct behavior:
> Add fallback test case

- test_cases/search_abbreviations.json
This uses different fields and synonyms from the corresponding autocomplete test, so should be tested separately. We don't appear to get it right currently
Connects https://github.com/OpenTransitTools/trimet-mod-pelias/issues/27
> Add search test case for 'Mt/Mount' in a _venue_ name

- test_cases/autocomplete_abbreviations.json
- test_cases/french_addresses.json
- test_cases/international.json
- test_cases/search_abbreviations.json
In https://github.com/pelias/schema/pull/453 we have some major improvements to the Pelias synonym system used to handle most abbreviations.
As a result of that work, 9 acceptance tests are now passing. This PR marks those as testing and if they represent a particular github issue that is clearly now resolved, marks that issue as fixed.
Some overall issues like https://github.com/pelias/api/issues/783 and https://github.com/pelias/schema/issues/301 for Spanish and French addresses are not marked as fixed, but we should go through the discussions there to see if they've effectively been resolved.
> Mark tests passing from synyonm overhaul

- test_cases/admin_translations.json
- test_cases/encoding.json
- test_cases/placeholder_sorting.json
It's been a while since we've run the acceptance tests with Placeholder built from recent data. Since then, some minor translation changes have snuck in.
> Placeholder updates

- test_cases/address_matching.json
- test_cases/address_parsing.json
- test_cases/admin_lookup.json
- test_cases/autocomplete_focus.json
- test_cases/autocomplete_streets.json
- test_cases/autocomplete_venues.json
- test_cases/labels.json
- test_cases/search.json
- test_cases/search_coarse.json
Over in https://github.com/pelias/labels/pull/39 we have completely redone the labels for New York City, and they should be essentially 100% correct now, with all the special cases handled.
This PR updates all the acceptance tests for those new labels, and also adds some additional label tests to make sure we continue to get all the really interesting special cases, especially those in Queens, correct going forward.
> Update tests for NYC Labels

- test_cases/autocomplete_multi_lang.json
This adds a test for finding [Edo Tokyo Museum](https://pelias.github.io/compare/#/v1/autocomplete?layers=venue&debug=1&text=Edo+Tokyo+Museum) via autocomplete.
Connects https://github.com/pelias/api/issues/1296#issuecomment-703679827
Connects https://github.com/pelias/api/pull/1493
> Add test for multi-word input in non-default language

- test_cases/autocomplete_iso2_to_iso3.json
As of this writing, Pelias stores and indexes in Elasticsearch _only_ the 3 character [ISO 3166-1](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) country code for every record.
For a select few countries, the 2 character code is not a prefix of the 3 character code (for example, Mexico is `MX`/`MEX`).
Most of Pelias can handle queries for either variant of the country code just fine.
However, the autocomplete endpoint currently does _not_ return any results if one of those few special two character codes is used.
While probably a fairly rare occurrence in actual usage, since they would generally appear at the very end of a query, it's nice to ensure these are handled properly.
This PR includes tests for 3 different autocomplete cases:
- query for a city
- two queries for …
> Add tests for 2 letter country code handling in autocomplete

- test_cases/address_parsing.json
- test_cases/admin_lookup.json
- test_cases/admin_translations.json
- test_cases/autocomplete_focus.json
- test_cases/confidence_score.json
- test_cases/exact_matches.json
- test_cases/placeholder_geometric_filters.json
- test_cases/search_abbreviations.json
- test_cases/search_iso2_to_iso3.json
- test_cases/search_postal_cities.json
- test_cases/search_street_centroids.json
- test_cases/tizen-sdk-geocoder.json
Thanks to https://github.com/pelias/openaddresses/pull/477 we have improved street name normalization for many common suffixes.
This change updates our acceptance tests based on those changes. There are quite a few changes, and they're all pretty positive. While hard to tell from the acceptance tests themselves, they generally come along with reduced duplicate results
> Adjust street suffixes for new normalization

- test_cases/admin_translations.json
- test_cases/autocomplete_abbreviations.json
This is a follow up to https://github.com/pelias/acceptance-tests/pull/536 that updates expected street names after the improved normalization in https://github.com/pelias/openaddresses/pull/477.
Looks like I missed a few!
> Fix more improved street names

- test_cases/search_poi.json
Union Square, NYC has long been a challenging query to get right.
The data is complex, scoring is important, and there are many other legitimate Union Squares to consider, both venues and neighbourhoods.
Connects https://github.com/pelias/pelias/issues/202
Connects https://github.com/pelias/pelias/issues/321
> Add several variations of Union Square tests

- test_cases/autocomplete_streets.json
- test_cases/labels.json
Thanks to our work in https://github.com/pelias/labels/pull/43 and https://github.com/pelias/labels/pull/45 we have improved labels in many cases.
Fortunately, because we learned long ago to prefer checking the `label` field in dedicated label acceptance-tests, there aren't too many places that need updating!
> Update tests for improved region labels

- test_cases/autocomplete_address.json
In https://github.com/pelias/openstreetmap/pull/549 we added some popularity scoring to important, well known addresses.
This adds some relevant tests for that functionality.
> Add address popularity tests

- test_cases/search_postalcodes.json
This adds tests for a particular type of postalcode we've had trouble with: those with a leading zero.
Tests are added to the existing 'search postalcode' suite, and a new 'autocomplete postalcode' suite is also created.
We have https://github.com/pelias/schema/pull/475 in progress which we hope can fix the current known issues.
Connects https://github.com/pelias/pelias/issues/898
> Add leading-zero postalcode tests

- test_cases/autocomplete_postalcodes.json
This adds autocomplete tests specifically around postalcode behavior.
Most of them were missed and I actually meant to commit them as part of https://github.com/pelias/acceptance-tests/pull/544. 😆 
Additionally, I've added one more test for an incomplete postalcode, to measure progress against https://github.com/pelias/pelias/issues/676.
We may be able to improve results with https://github.com/pelias/api/pull/1514
> Add postalcode autocomplete tests

- test_cases/deduplication.json
This adds some simple tests that assert 'City of X' style results do not appear in autocomplete queries because of Geonames records.
Connects https://github.com/pelias/geonames/issues/395
> Add Geonames 'City of X' deduplication cases

- test_cases/autocomplete_postalcodes.json
This PR improves our postal code tests with several types of changes.
First, tests requiring [supporting leading-zeros in postalcodes](https://github.com/pelias/pelias/issues/898) are now marked passing, as that was fixed by https://github.com/pelias/schema/pull/475. 🎉 
Additionally, a bunch of new postalcode tests were added. I picked a couple fairly random places and tried to find reasonable approximations of postalcodes:
- Manchester, England (before I noticed we already had British postalcode tests)
- London, Ontario, Canada
- Berlin, Germany
- Amsterdam, Netherlands
- Melbourne, Australia
Many of these tests are marked as failing, generally due to data missing by default from current Pelias installations. In Germany, for example, we have all the postalcodes but not coordinates for …
> Add and update Postalcode tests

- test_cases/address_parsing.json
- test_cases/washington_dc.json
In recent work such as https://github.com/pelias/openaddresses/pull/486 and https://github.com/pelias/openstreetmap/pull/560, we've attempted to ensure that street directionals (specifically the diagonals like Southwest, Northeast, etc) are handled consistently.
The intention is that these directionals are always _abbreviated_.
Our acceptance tests have long had some inconsistencies in how they handle directionals that this exposes:
- first of all, any tests that expected both `Somestreet NW` and `Somestreet Northwest` to be present need to be updated
- Some tests did not properly use our [normalizers](https://github.com/pelias/fuzzy-tester#normalizers) or did not handle a normalizer related bug (https://github.com/pelias/fuzzy-tester/issues/201)
> Improve tests with directionals in streetnames

- test_cases/autocomplete_address.json
- test_cases/autocomplete_multi_lang.json
- test_cases/autocomplete_postalcodes.json
- test_cases/placeholder_sorting.json
- test_cases/search_city_country.json
- test_cases/structured_geocoding.json
Our usual periodic round of cleanup for acceptance tests that have changed state over time.
This PR includes lots of marking improvements as passing. Some around language features, some around postal code handling, etc. Details are in the individual commits.
> August test updates

- test_cases/address_type.json
- test_cases/autocomplete_focus.json
- test_cases/international.json
- test_cases/placeholder_general.json
- test_cases/placeholder_sorting.json
- test_cases/search_poi.json
- test_cases/search_postalcodes.json
- test_cases/wof_countries.json
- test_cases/wof_neighbourhoods.json
The usual round of periodic acceptance test updates. There are still a few more to do (as always), but these are the main ones.
Details are in the individual commits but here are some highlights:
- Luxembourg city was recently renamed from `Luxembourg City` to `Luxembourg` in WOF. This is a positive change and means Luxembourg city/country deduplication can kick in, preferring the city as per our usual rules
- A couple focus point tests are passing after https://github.com/pelias/whosonfirst/pull/529
- Various other name changes in WOF and improvements to address formatting from https://github.com/pelias/api/pull/1549
> November test updates

- test_cases/deduplication.json
This test case came out of evaluating https://github.com/pelias/api/pull/1607. It passes with the current API master branch, fails with https://github.com/pelias/api/pull/1607, but passes with https://github.com/pelias/api/pull/1612
> Add an example of deduplication where order matters

- test_cases/placeholder_general.json
These tests have drifted a bit over time, and don't really well represent the data we now have.
Unfortunately what looks like the intent of these tests is no longer achieved, so they are marked failing.
The results improve with our current deduplication work, but won't be fully correct until we update WOF and ensure https://spelunker.whosonfirst.org/id/1360756237/ (City of Durham locality) is parented by https://spelunker.whosonfirst.org/id/404448031/ (City of Durham localadmin)
> Update 'County Durham' tests

- test_cases/landmarks.json
We have quite a few Statue of Liberty tests, but this one had an incorrect label from back in the days before we handled all the special cases in NYC.
> Fix Statue of Liberty landmark tests

- test_cases/search_poi.json
These tests have not had great pass rate until https://github.com/pelias/api/pull/1620, so we didn't know that the `distanceThresh` value for the coordinate checks weren't quite correct.
Hopefully they will be passing soon!
> Improve PHX airport POI tests

- test_cases/autocomplete_postalcodes.json
- test_cases/search_postalcodes.json
this PR updates *both* the `/v1/autocomplete` & `/v1/search` test cases for postalcodes:
- add some DEU postalcodes and mark any previously failing DEU cases as passing
- add some additional GBR postalcodes
- update USA 90210 test, this case has been passing for some time on geocode.earth but was still marked as failing
> update postalcode test cases

- test_cases/confidence_score.json
openaddresses data will now always have the ordinal appended for numeric street names
links: https://github.com/pelias/openaddresses/pull/508
> ordinals: update street name format

- test_cases/search_boundary_coutry.json
- test_cases/structured_boundary_country.json
This adds tests cases for the `boundary.country` parameter on the `search`, and `structured` API endpoints. Previously, we only tested `autocomplete`.
In addition, it adds tests for records that only have `parent.dependency_a` values, not `parent.country_a`, which require https://github.com/pelias/api/pull/1622 to pass.
> Add more `boundary.country` test cases

- test_cases/autocomplete_endonyms.json
These test cases cover the functionality discussed in https://github.com/pelias/wof-admin-lookup/pull/314
I managed to reduce it down to 4 tests which cover the scope of the work:
*country - where the `name:default` is an Exonym*
- query for the exonym
- query for the endonym
*locality - where the `name:default` is an Endonym*
- query for the endonym
- query in English
> endonyms: add test cases covering endonyms/exonyms

- test_cases/search_alphanumeric_housenumber.json
A little cleanup to our alphanumeric housenumber tests to go with https://github.com/pelias/api/pull/1683 / https://github.com/pelias/query/pull/139.
The major changes are:
- setting `priorityThresh` to 1, as we really want the desired result to sort _first_
- fixing a test in Belarus that does not seem to line up with the streetname in OSM
- Adding a new test for the `Kinkerstraat 175F` case from https://github.com/pelias/pelias/issues/810
Minor changes:
- renaming the test suite to be prefixed by search_. This is a bit random but I think our test suites should be for a specific endpoint. Most already are, so this just adds to that trend.
- Adjust normalizers to make matching housenumbers easier, in this case between `14/a` in the results and `14a` in the test
After …
> Alphanumeric housenumber test improvements
